classes Autor e Coleção de Autores e seus testes
IgorNascAlves/Edigi-Pratica-Deliberada pull request #1
Opened 2020-06-25 19:17 UTC by IgorNascAlves

2020-06-26 18:24 UTC, wandersonmaceds requested changes

2020-06-26 18:24 UTC, wandersonmaceds commented on test/test_author.py
> +        self.assertEqual(email, author1.email)
Parece que estes testes tentam confirmar se a lógica de criação de um autor está correta, então me parece que deveria ser um teste só. É uma única lógica, se prestar atenção.

2020-06-26 18:24 UTC, wandersonmaceds commented on test/test_collection_authors.py
> +        self.assertEqual(size, len(collection))
Não entendi a utilidade deste teste.

2020-07-01 16:13 UTC, wandersonmaceds reviewed
Algumas questões mais abstratas pra gente discutir um pouco.

2020-07-01 16:13 UTC, wandersonmaceds commented on test/test_author.py
>          self.assertEqual(name, author1.name)
Isso é o suficiente para garantir que a criação do autor foi um sucesso?

2020-07-01 16:13 UTC, wandersonmaceds commented on test/test_collection_authors.py
>          self.assertEqual(size, len(collection))
Confesso que eu não acho muito orientado a objetos que uma coleção não saiba dizer o seu tamanho e sim depender de algo externo para calcular o valor. Aliás, qual a utilidade de saber que a coleção cresce quando você usa o método add?

2020-07-07 17:18 UTC, wandersonmaceds approved these changes

2020-07-07 17:18 UTC, wandersonmaceds commented on test/test_author.py
> +        self.assertRaises(ValueError, Author, name, email)
que chique ele permitir fazer assim

2020-07-07 17:20 UTC, IgorNascAlves commented on test/test_author.py
> +        self.assertRaises(ValueError, Author, name, email)
Sim, mas fiquei na duvida se atrapalha a legibilidade no que está acontecendo no teste.

2020-07-07 17:25 UTC, merged