Cadastrando um novo livro
IgorNascAlves/Edigi-Pratica-Deliberada pull request #3
Opened 2020-07-29 18:04 UTC by IgorNascAlves

2020-07-30 19:06 UTC, wandersonmaceds requested changes

2020-07-30 19:06 UTC, wandersonmaceds commented on src/author.py
> +        if is_it_null_ou_empty(name):
haha, o it gera concordância mas normalmente não é usado, é comum ver IsNullOrEmpty por exemplo (o case depende da linguagem), mas ficou o ou ali em vez de or né?

2020-07-30 19:06 UTC, wandersonmaceds commented on src/validation_utils.py
> +        raise Exception("ISBN invalid - must star with " + start_with_one)
Então, não vi a utilidade de separar essas validações muito específicas aqui. O valida_format até poderia esconder a regex, mas de alguma forma, você teria que passar a regex para o método. Acho que essas validações poderiam estar direto dentro da classe mesmo. 

O validation_utils eu vejo como um lugar para colocar coisas que podem ser reutilizadas em vários lugares, como o isNullOrEmpty.

2020-07-30 19:59 UTC, IgorNascAlves commented on src/validation_utils.py
> +        raise Exception("ISBN invalid - must star with " + start_with_one)
Concordo, são muito específicos e dificilmente vão ser utilizados por outra parte do código.

2020-07-31 14:08 UTC, wandersonmaceds requested changes

2020-07-31 14:08 UTC, wandersonmaceds commented on src/book.py
> +            raise Exception("ISBN invalid - must star with " + start_with_one)
Aqui você só moveu o código, confesso que esperava algo mais, exemplo: a regex sozinha ela pode validar tanto o padrão quanto algo fixo que pode estar dentro da string, algo como `^978` já poderia resolver e você teria apenas uma função de validação do isbn ao invés de 3.

Esse start_if_one eu não sei se vale a pena ser isolado, me parece uma solução muito verbosa para o problema.

2020-07-31 15:44 UTC, IgorNascAlves commented on src/book.py
> +            raise Exception("ISBN invalid - must star with " + start_with_one)
Obrigado, agora consegui visualizar, não estava conseguindo enxergar que poderia unir essas duas validações em uma.

2020-08-02 13:17 UTC, wandersonmaceds approved these changes

2020-08-04 14:43 UTC, merged