criação da classe carrinho e seus testes
IgorNascAlves/Edigi-Pratica-Deliberada pull request #5
Opened 2020-08-20 18:25 UTC by IgorNascAlves

2020-08-20 19:25 UTC, wandersonmaceds requested changes

2020-08-20 19:25 UTC, wandersonmaceds commented on src/cart.py
> +        self.__total += book.price * amount
Acho armadilha você calcular o total diretamente na adição do produto, se houver lógicas que mudem esse calculo, você altera um lugar que não deveria. Este método, se pensar linha a linha, já faz bastante coisa. Até mesmo sees uso da collection eu removeria daqui, o Cart só deveria saber guardar os itens da venda e calcular o total, se ele precisar buscar no Dao também, você dá mais de uma razão pra essa classe mudar.

2020-08-21 13:14 UTC, IgorNascAlves commented on src/cart.py
> +        self.__total += book.price * amount
Déjà vu :smile:

2020-08-21 17:28 UTC, wandersonmaceds requested changes

2020-08-21 17:28 UTC, wandersonmaceds commented on src/cart.py
> +            self.__total += book.price * amount
Por que não um getTotal, por que você ainda depende de um atributo que pode ficar desatualizado.

2020-08-21 19:17 UTC, IgorNascAlves commented on src/cart.py
> +            self.__total += book.price * amount
Gostei da ideia.

2020-08-24 17:56 UTC, wandersonmaceds approved these changes

2020-08-24 17:56 UTC, wandersonmaceds commented on src/cart.py
> +        return total
Podia ser só get_total

2020-09-03 17:56 UTC, merged